### PR TITLE
fixed the nav bar

### PR DESCRIPTION
**Pull request by chaursiyasanjeet**
Hey, the Navbar is fixed Now, it is not moving on scrolling.
I can also modify opacity of the Navbar if you want.
image

### CODE REVIEW

**Comment by chaursiyasanjeet** [comment]
waiting for your review

**Comment by Rajat2024** [comment]
[ok](https://rajat-singh.onrender.com/)

**Comment by Rajat2024** [comment]
https://rajat-singh.onrender.com/

**Comment by chaursiyasanjeet** [comment]
thank you @Rajat2024

**Pull request merged**
