### PR TITLE
add : new footer created and attached ! 

### PR DESCRIPTION
**Pull request by rohitroy-github**

### CODE REVIEW

**Comment by Rajat2024** [comment]
Add some photo to show UI

**Comment by rohitroy-github** [comment]
Sure > 

image

**Comment by Rajat2024** [comment]
Ok it will merge tonight 
Plz wait

**Comment by Rajat2024** [comment]
image
footer is not working in all the page

**Comment by rohitroy-github** [comment]
Checking !

**Comment by rohitroy-github** [comment]
@Rajat2024 I have fixed the issues. Please merge it now.

**Comment by Rajat2024** [comment]
whole UI is changed and it is not looking good

**Pull request closed without merging**
